import '@/styles/globals.css';

import classNames from 'classnames';
import type { Metadata } from 'next';
import type { PropsWithChildren } from 'react';

import { pretendard } from '@/styles/font';
import Banner from '@/components/Banner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ko">
      <body className={classNames(pretendard.className)}>
        <Banner />
        {children}
      </body>
    </html>
  );
}
